//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10", IsNullable = false)]
public partial class PurchasingForm
{
    private string fileNameField;

    private string contentTypeNameField;

    private double totalAmountField;

    private bool totalAmountFieldSpecified;

    private System.Nullable<bool> isLargerThan0Field;

    private bool isLargerThan0FieldSpecified;

    private bool transferToSRMField;

    private bool transferToSRMFieldSpecified;

    private string reviewCostAssignmentField;

    private string lRFNumberField;

    private string lRFTitleField;

    private string lRFLinkField;

    private string agrrementLinkField;

    private string contractNumberField;

    private string sAPSupplierNumberField;

    private CostCenterCharge[] group11Field;

    private System.Nullable<System.DateTime> effectiveDateField;

    private bool effectiveDateFieldSpecified;

    private System.Nullable<System.DateTime> expirationDateField;

    private bool expirationDateFieldSpecified;

    private Person[] requestorField;

    private string currentUserHiddenField;

    private string currentUserEmailHiddenField;

    private string requestorEmailHiddenField;

    private string requestorAccountNameHiddenField;

    private string userIDField;

    private string currencyField;

    private bool isSubmittedField;

    private bool isSubmittedFieldSpecified;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    public double TotalAmount
    {
        get
        {
            return this.totalAmountField;
        }
        set
        {
            this.totalAmountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalAmountSpecified
    {
        get
        {
            return this.totalAmountFieldSpecified;
        }
        set
        {
            this.totalAmountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Nullable<bool> isLargerThan0
    {
        get
        {
            return this.isLargerThan0Field;
        }
        set
        {
            this.isLargerThan0Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isLargerThan0Specified
    {
        get
        {
            return this.isLargerThan0FieldSpecified;
        }
        set
        {
            this.isLargerThan0FieldSpecified = value;
        }
    }

    /// <remarks/>
    public bool TransferToSRM
    {
        get
        {
            return this.transferToSRMField;
        }
        set
        {
            this.transferToSRMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransferToSRMSpecified
    {
        get
        {
            return this.transferToSRMFieldSpecified;
        }
        set
        {
            this.transferToSRMFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string FileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }

    /// <remarks/>
    public string ReviewCostAssignment
    {
        get
        {
            return this.reviewCostAssignmentField;
        }
        set
        {
            this.reviewCostAssignmentField = value;
        }
    }

       /// <remarks/>
    public string ContentTypeName
    {
        get
        {
            return this.contentTypeNameField;
        }
        set
        {
            this.contentTypeNameField = value;
        }
    }


    /// <remarks/>
    public string LRFNumber
    {
        get
        {
            return this.lRFNumberField;
        }
        set
        {
            this.lRFNumberField = value;
        }
    }

    /// <remarks/>
    public string LRFTitle
    {
        get
        {
            return this.lRFTitleField;
        }
        set
        {
            this.lRFTitleField = value;
        }
    }


    /// <remarks/>
    public string LRFLink
    {
        get
        {
            return this.lRFLinkField;
        }
        set
        {
            this.lRFLinkField = value;
        }
    }


    /// <remarks/>
    public string AgrrementLink
    {
        get
        {
            return this.agrrementLinkField;
        }
        set
        {
            this.agrrementLinkField = value;
        }
    }


    /// <remarks/>
    public string ContractNumber
    {
        get
        {
            return this.contractNumberField;
        }
        set
        {
            this.contractNumberField = value;
        }
    }

    /// <remarks/>
    public string SAPSupplierNumber
    {
        get
        {
            return this.sAPSupplierNumberField;
        }
        set
        {
            this.sAPSupplierNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CostCenterCharge", IsNullable = false)]
    public CostCenterCharge[] group11
    {
        get
        {
            return this.group11Field;
        }
        set
        {
            this.group11Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
    public System.Nullable<System.DateTime> EffectiveDate
    {
        get
        {
            return this.effectiveDateField;
        }
        set
        {
            this.effectiveDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EffectiveDateSpecified
    {
        get
        {
            return this.effectiveDateFieldSpecified;
        }
        set
        {
            this.effectiveDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
    public System.Nullable<System.DateTime> ExpirationDate
    {
        get
        {
            return this.expirationDateField;
        }
        set
        {
            this.expirationDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExpirationDateSpecified
    {
        get
        {
            return this.expirationDateFieldSpecified;
        }
        set
        {
            this.expirationDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Person", Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable = false)]
    public Person[] Requestor
    {
        get
        {
            return this.requestorField;
        }
        set
        {
            this.requestorField = value;
        }
    }

    /// <remarks/>
    public string CurrentUserHidden
    {
        get
        {
            return this.currentUserHiddenField;
        }
        set
        {
            this.currentUserHiddenField = value;
        }
    }

    /// <remarks/>
    public string CurrentUserEmailHidden
    {
        get
        {
            return this.currentUserEmailHiddenField;
        }
        set
        {
            this.currentUserEmailHiddenField = value;
        }
    }

    /// <remarks/>
    public string RequestorEmailHidden
    {
        get
        {
            return this.requestorEmailHiddenField;
        }
        set
        {
            this.requestorEmailHiddenField = value;
        }
    }

    /// <remarks/>
    public string RequestorAccountNameHidden
    {
        get
        {
            return this.requestorAccountNameHiddenField;
        }
        set
        {
            this.requestorAccountNameHiddenField = value;
        }
    }

    /// <remarks/>
    public string UserID
    {
        get
        {
            return this.userIDField;
        }
        set
        {
            this.userIDField = value;
        }
    }

    /// <remarks/>
    public string Currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    public bool IsSubmitted
    {
        get
        {
            return this.isSubmittedField;
        }
        set
        {
            this.isSubmittedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsSubmittedSpecified
    {
        get
        {
            return this.isSubmittedFieldSpecified;
        }
        set
        {
            this.isSubmittedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10", IsNullable = false)]
public partial class CostCenterCharge
{

    private CostCenterDetails[] costCenterEntryField;

    private string costCenterField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CostCenterDetails", IsNullable = false)]
    public CostCenterDetails[] CostCenterEntry
    {
        get
        {
            return this.costCenterEntryField;
        }
        set
        {
            this.costCenterEntryField = value;
        }
    }

    /// <remarks/>
    public string CostCenter
    {
        get
        {
            return this.costCenterField;
        }
        set
        {
            this.costCenterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10", IsNullable = false)]
public partial class CostCenterDetails
{

    private string amountField;

    private string descriptionField;

    private string productCategoryField;

    /// <remarks/>
    public string Amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string ProductCategory
    {
        get
        {
            return this.productCategoryField;
        }
        set
        {
            this.productCategoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable = false)]
public partial class Person
{

    private string displayNameField;

    private string accountIdField;

    private string accountTypeField;

    /// <remarks/>
    public string DisplayName
    {
        get
        {
            return this.displayNameField;
        }
        set
        {
            this.displayNameField = value;
        }
    }

    /// <remarks/>
    public string AccountId
    {
        get
        {
            return this.accountIdField;
        }
        set
        {
            this.accountIdField = value;
        }
    }

    /// <remarks/>
    public string AccountType
    {
        get
        {
            return this.accountTypeField;
        }
        set
        {
            this.accountTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10", IsNullable = false)]
public partial class group11
{

    private CostCenterCharge[] costCenterChargeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CostCenterCharge")]
    public CostCenterCharge[] CostCenterCharge
    {
        get
        {
            return this.costCenterChargeField;
        }
        set
        {
            this.costCenterChargeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10", IsNullable = false)]
public partial class CostCenterEntry
{

    private CostCenterDetails[] costCenterDetailsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CostCenterDetails")]
    public CostCenterDetails[] CostCenterDetails
    {
        get
        {
            return this.costCenterDetailsField;
        }
        set
        {
            this.costCenterDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2003/myXSD/2011-10-05T00:10:10", IsNullable = false)]
public partial class Requestor
{

    private Person[] personField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Person", Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
    public Person[] Person
    {
        get
        {
            return this.personField;
        }
        set
        {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable = false)]
public partial class BDCAssociatedEntity
{

    private BDCEntity[] bDCEntityField;

    private string entityNamespaceField;

    private string entityNameField;

    private string systemInstanceNameField;

    private string associationNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BDCEntity")]
    public BDCEntity[] BDCEntity
    {
        get
        {
            return this.bDCEntityField;
        }
        set
        {
            this.bDCEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string EntityNamespace
    {
        get
        {
            return this.entityNamespaceField;
        }
        set
        {
            this.entityNamespaceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string EntityName
    {
        get
        {
            return this.entityNameField;
        }
        set
        {
            this.entityNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string SystemInstanceName
    {
        get
        {
            return this.systemInstanceNameField;
        }
        set
        {
            this.systemInstanceNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string AssociationName
    {
        get
        {
            return this.associationNameField;
        }
        set
        {
            this.associationNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable = false)]
public partial class BDCEntity
{

    private string entityDisplayNameField;

    private string entityInstanceReferenceField;

    private string entityId1Field;

    private string entityId2Field;

    private string entityId3Field;

    private string entityId4Field;

    private string entityId5Field;

    /// <remarks/>
    public string EntityDisplayName
    {
        get
        {
            return this.entityDisplayNameField;
        }
        set
        {
            this.entityDisplayNameField = value;
        }
    }

    /// <remarks/>
    public string EntityInstanceReference
    {
        get
        {
            return this.entityInstanceReferenceField;
        }
        set
        {
            this.entityInstanceReferenceField = value;
        }
    }

    /// <remarks/>
    public string EntityId1
    {
        get
        {
            return this.entityId1Field;
        }
        set
        {
            this.entityId1Field = value;
        }
    }

    /// <remarks/>
    public string EntityId2
    {
        get
        {
            return this.entityId2Field;
        }
        set
        {
            this.entityId2Field = value;
        }
    }

    /// <remarks/>
    public string EntityId3
    {
        get
        {
            return this.entityId3Field;
        }
        set
        {
            this.entityId3Field = value;
        }
    }

    /// <remarks/>
    public string EntityId4
    {
        get
        {
            return this.entityId4Field;
        }
        set
        {
            this.entityId4Field = value;
        }
    }

    /// <remarks/>
    public string EntityId5
    {
        get
        {
            return this.entityId5Field;
        }
        set
        {
            this.entityId5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable = false)]
public partial class Terms
{

    private TermInfo[] termInfoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TermInfo")]
    public TermInfo[] TermInfo
    {
        get
        {
            return this.termInfoField;
        }
        set
        {
            this.termInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable = false)]
public partial class TermInfo
{

    private string termNameField;

    private string termIdField;

    /// <remarks/>
    public string TermName
    {
        get
        {
            return this.termNameField;
        }
        set
        {
            this.termNameField = value;
        }
    }

    /// <remarks/>
    public string TermId
    {
        get
        {
            return this.termIdField;
        }
        set
        {
            this.termIdField = value;
        }
    }
}
