//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elan.SharePoint.LRFApproval.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Executive Approvers")]
        public string ListTitleExecutiveApprovers {
            get {
                return ((string)(this["ListTitleExecutiveApprovers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Financial Assignment")]
        public string ListTitleFinancialAssignment {
            get {
                return ((string)(this["ListTitleFinancialAssignment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrgBand")]
        public string UserprofileFieldBand {
            get {
                return ((string)(this["UserprofileFieldBand"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AuthAppAmt")]
        public string UserProfileFieldAuthAmount {
            get {
                return ((string)(this["UserProfileFieldAuthAmount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Approvers")]
        public string FieldLRFFormApprovers {
            get {
                return ((string)(this["FieldLRFFormApprovers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VP Finance")]
        public string VPOfFinanceTitle {
            get {
                return ((string)(this["VPOfFinanceTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EstimatedAmount")]
        public string FieldLRFFormRequestAmount {
            get {
                return ((string)(this["FieldLRFFormRequestAmount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legal Request Forms")]
        public string ListTitleLRF {
            get {
                return ((string)(this["ListTitleLRF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User")]
        public string FieldUser {
            get {
                return ((string)(this["FieldUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostCenter")]
        public string FieldCostCenter {
            get {
                return ((string)(this["FieldCostCenter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeptApprovers")]
        public string FieldLRFDeptApprovers {
            get {
                return ((string)(this["FieldLRFDeptApprovers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FinancialApprovers")]
        public string FieldLRFFinancialApprovers {
            get {
                return ((string)(this["FieldLRFFinancialApprovers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExecutiveApprovers")]
        public string FieldLRFExecutiveApprovers {
            get {
                return ((string)(this["FieldLRFExecutiveApprovers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomID")]
        public string QSRequestSummaryPage {
            get {
                return ((string)(this["QSRequestSummaryPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRFFileStatusHidden")]
        public string FieldLRFStatus {
            get {
                return ((string)(this["FieldLRFStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Agement_x0020_Status")]
        public string FieldAgreementStatus {
            get {
                return ((string)(this["FieldAgreementStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostCenterSAP")]
        public string ListTitleCostCenterSAP {
            get {
                return ((string)(this["ListTitleCostCenterSAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("description")]
        public string FieldCostCenterDescription {
            get {
                return ((string)(this["FieldCostCenterDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://phxsp10wd-vn01:2000")]
        public string BDCEntityNamespace {
            get {
                return ((string)(this["BDCEntityNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostCenterSAP")]
        public string BDCEntityName {
            get {
                return ((string)(this["BDCEntityName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Read List")]
        public string BDCFinderView {
            get {
                return ((string)(this["BDCFinderView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRF Issues Log")]
        public string ListTitleLRFIssuesLog {
            get {
                return ((string)(this["ListTitleLRFIssuesLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRFID")]
        public string FieldLRFIssueID {
            get {
                return ((string)(this["FieldLRFIssueID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRFUrl")]
        public string FieldLRFIssueUrl {
            get {
                return ((string)(this["FieldLRFIssueUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostCenterSuperUser_")]
        public string GroupCostCenterSuperUserPrefix {
            get {
                return ((string)(this["GroupCostCenterSuperUserPrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostCenterUser_")]
        public string GroupCostCenterUserPrefix {
            get {
                return ((string)(this["GroupCostCenterUserPrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CostCenterProfile_")]
        public string GroupCostCenterProfilePrefix {
            get {
                return ((string)(this["GroupCostCenterProfilePrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRF super users")]
        public string GroupLRFSuperUsers {
            get {
                return ((string)(this["GroupLRFSuperUsers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legal Team")]
        public string GroupLegalTeam {
            get {
                return ((string)(this["GroupLegalTeam"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legal Center Owners")]
        public string GroupLegalCenterOwner {
            get {
                return ((string)(this["GroupLegalCenterOwner"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Finance Team")]
        public string GroupFinanceTeam {
            get {
                return ((string)(this["GroupFinanceTeam"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RequestorHidden")]
        public string FieldLRRequestor {
            get {
                return ((string)(this["FieldLRRequestor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error")]
        public string FieldLRFIssueErrorDetails {
            get {
                return ((string)(this["FieldLRFIssueErrorDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserType")]
        public string FieldUserType {
            get {
                return ((string)(this["FieldUserType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Analyst")]
        public string FieldValueAnalyst {
            get {
                return ((string)(this["FieldValueAnalyst"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Management")]
        public string FieldValueManagement {
            get {
                return ((string)(this["FieldValueManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormIssues")]
        public string FieldItemIssues {
            get {
                return ((string)(this["FieldItemIssues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Saved LRFs")]
        public string ListTitleSavedLRFs {
            get {
                return ((string)(this["ListTitleSavedLRFs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Agreements")]
        public string ListTitleAgreements {
            get {
                return ((string)(this["ListTitleAgreements"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Assigned_x0020_To_x0020_Legal")]
        public string FieldAssignedToLegal {
            get {
                return ((string)(this["FieldAssignedToLegal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legal Cost Center Assignment")]
        public string ListTitleLegalCostCenterAssignment {
            get {
                return ((string)(this["ListTitleLegalCostCenterAssignment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Group")]
        public string FieldLegalCostCenterAssignmentGroup {
            get {
                return ((string)(this["FieldLegalCostCenterAssignmentGroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legal Request Form Workflow")]
        public string WorkFlowName {
            get {
                return ((string)(this["WorkFlowName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Last_x0020_Dept_x0020_Approver")]
        public string FieldLastDeptApprover {
            get {
                return ((string)(this["FieldLastDeptApprover"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Last_x0020_Financial_x0020_Approver")]
        public string FieldLastFinancialApprover {
            get {
                return ((string)(this["FieldLastFinancialApprover"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purchasing Team")]
        public string GroupPurchasingTeam {
            get {
                return ((string)(this["GroupPurchasingTeam"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Request_x0020_Status")]
        public string FieldRequestStatus {
            get {
                return ((string)(this["FieldRequestStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purchasing Request Forms")]
        public string ListTitlePurchasingRequests {
            get {
                return ((string)(this["ListTitlePurchasingRequests"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRF Requestor")]
        public string FieldAgreementsLRFRequestor {
            get {
                return ((string)(this["FieldAgreementsLRFRequestor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AgreementId")]
        public string FieldAgreementContractNumber {
            get {
                return ((string)(this["FieldAgreementContractNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRF_X0020_Title")]
        public string FieldAgreementLRFTitle {
            get {
                return ((string)(this["FieldAgreementLRFTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAP Supplier Number")]
        public string FieldAgreementSupplier {
            get {
                return ((string)(this["FieldAgreementSupplier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Effective_x0020_Date")]
        public string FieldAgreementEffectiveDate {
            get {
                return ((string)(this["FieldAgreementEffectiveDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Expire_x0020_Date_x0020_Revised")]
        public string FieldAgreementExpirationDateRevised {
            get {
                return ((string)(this["FieldAgreementExpirationDateRevised"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Total Amount")]
        public string FieldAgreementNotToExceedValue {
            get {
                return ((string)(this["FieldAgreementNotToExceedValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Actual Value")]
        public string FieldAgreementActualValue {
            get {
                return ((string)(this["FieldAgreementActualValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRF Ref:ID")]
        public string FieldAgreementLRFID {
            get {
                return ((string)(this["FieldAgreementLRFID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TransferToSRM")]
        public string FieldAgreementTransferToSRM {
            get {
                return ((string)(this["FieldAgreementTransferToSRM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USD")]
        public string DefaultCurrency {
            get {
                return ((string)(this["DefaultCurrency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purchasing Info")]
        public string CTPurchasingInfo {
            get {
                return ((string)(this["CTPurchasingInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LinkFilename")]
        public string FieldLRFLinkFilename {
            get {
                return ((string)(this["FieldLRFLinkFilename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/FormServerTemplates/Purchasing%20Info.xsn")]
        public string FormTemplateUrlPurchasingInfo {
            get {
                return ((string)(this["FormTemplateUrlPurchasingInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PurchasingFromGenerated")]
        public string FieldAgreementPurchasingFromGenerated {
            get {
                return ((string)(this["FieldAgreementPurchasingFromGenerated"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legal_x0020_Owner")]
        public string FieldLegalOwner {
            get {
                return ((string)(this["FieldLegalOwner"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Request Status")]
        public string ListTitleRequestStatus {
            get {
                return ((string)(this["ListTitleRequestStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legal_x0020_Request_x0020_Status")]
        public string FieldLegalRequestStatus {
            get {
                return ((string)(this["FieldLegalRequestStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Approved_x003f_")]
        public string FieldApproved {
            get {
                return ((string)(this["FieldApproved"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LRF Submitter")]
        public string FieldAgreementsLRFSubmitter {
            get {
                return ((string)(this["FieldAgreementsLRFSubmitter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Business Contact")]
        public string FieldAgreementsBusinessContact {
            get {
                return ((string)(this["FieldAgreementsBusinessContact"]));
            }
        }
    }
}
